#!/usr/bin/env python3
"""
merge_upstream_defconfig.py - Pure Kernel Defconfig Merger & Upstream Synchronizer
Automates merging of upstream PixelOS modular defconfig layers with Pure Kernel
ISO optimizations, ReSukiSU, and SuSFS configurations.
"""

import os
import sys
import subprocess

def parse_config_lines(lines):
    cfg = {}
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if line.startswith('# CONFIG_') and ' is not set' in line:
            opt = line.replace('# CONFIG_', '').replace(' is not set', '').strip()
            cfg[opt] = 'n'
        elif line.startswith('CONFIG_') and '=' in line:
            k, v = line[7:].split('=', 1)
            cfg[k.strip()] = v.strip()
    return cfg

def parse_config_file(filepath):
    if not os.path.exists(filepath):
        print(f"[!] Warning: Config file not found: {filepath}")
        return {}
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        return parse_config_lines(f.readlines())

def merge_defconfig(base_dir="."):
    print("=== Pure Kernel Defconfig Upstream Merger ===")
    
    kona_path = os.path.join(base_dir, "arch/arm64/configs/vendor/kona-perf_defconfig")
    common_path = os.path.join(base_dir, "arch/arm64/configs/vendor/xiaomi/sm8250-common.config")
    alioth_path = os.path.join(base_dir, "arch/arm64/configs/vendor/xiaomi/alioth.config")
    target_path = os.path.join(base_dir, "arch/arm64/configs/alioth_defconfig")
    
    # 1. Start with existing full alioth_defconfig (or empty if creating fresh)
    merged = parse_config_file(target_path)
    
    # 2. Overlay upstream modular configs (in priority order: kona -> common -> alioth)
    kona_cfg = parse_config_file(kona_path)
    common_cfg = parse_config_file(common_path)
    alioth_cfg = parse_config_file(alioth_path)
    
    merged.update(kona_cfg)
    merged.update(common_cfg)
    merged.update(alioth_cfg)
    
    # 3. Apply Pure Kernel ISO Standard, Hardware Protection & Root/Stealth Overrides
    overrides = {
        # --- Root & Stealth (ReSukiSU + SuSFS v2.3.0) ---
        "KSU": "y",
        "KSU_SUSFS": "y",
        "THREAD_INFO_IN_TASK": "y",
        "CFI": "n",
        "CFI_CLANG": "n",
        "CFI_PERMISSIVE": "y",
        "PID_NS": "y",
        "NAMESPACES": "y",
        "USER_NS": "y",
        
        # --- Hardware Power, Battery & Charging (Anti-Bootloop Gates) ---
        "MACH_XIAOMI_ALIOTH": "y",
        "BATT_VERIFY_BY_DS28E16": "y",
        "BQ2597X_CHARGE_PUMP": "y",
        "ONEWIRE_GPIO": "y",
        "REGULATOR_PM8008": "y",
        "REGULATOR_QCOM_RPMH": "y",
        "BUILD_ARM64_DT_OVERLAY": "y",
        "BACKLIGHT_KTZ8866": "y",
        "BACKLIGHT_DUALKTZ8866": "n",       # Must be disabled on single-panel Alioth
        
        # --- Storage & Filesystem (PixelOS Modern EROFS & F2FS) ---
        "EROFS_FS": "y",
        "EROFS_FS_PCPU_KTHREAD": "y",
        "EROFS_FS_PCPU_KTHREAD_HIPRI": "y",
        "EXFAT_FS": "y",
        "F2FS_FS": "y",
        "F2FS_UNFAIR_RWSEM": "n",           # Fair RWSEM checkpoint protection
        
        # --- Touchscreen & Double Tap to Wake (DTTW) ---
        "TOUCHSCREEN_COMMON": "y",
        "TOUCHSCREEN_FOCALTECH": "y",
        "TOUCHSCREEN_XIAOMI_TOUCHFEATURE": "y",
        "TOUCHSCREEN_SUPPORT_NEW_GAME_MODE": "y",
        
        # --- Performance & Latency Optimizations ---
        "ARM_ARCH_TIMER_VCT_ACCESS": "y",   # Direct userspace CNTVCT_EL0 timer for ART/Choreographer
        "ARM64_SVE": "n",                   # SM8250 Kryo 585 has no SVE; prune context switch overhead
        "CRYPTO_CRC32_ARM64_CE": "y",       # Hardware-accelerated CRC32
        "TCP_CONG_ADVANCED": "y",
        "TCP_CONG_BBR": "y",
        "TCP_CONG_WESTWOOD": "y",
        
        # --- Security & Memory Hardening (ISO 27001) ---
        "SLAB_FREELIST_HARDENED": "y",
        "SLAB_FREELIST_RANDOM": "y",
        "HARDEN_EL2_VECTORS": "y",
        
        # --- Debug Pruning & Build Stability ---
        "SPMI_MSM_PMIC_ARB_DEBUG": "n",
        "DEBUG_LIST": "n",
        "BPF_PRELOAD": "n",
        "BPF_PRELOAD_UMD": "n",
        "BBG": "n",                         # Disable broken Baseband-guard
        "REKERNEL": "n",
    }
    
    for k, v in overrides.items():
        merged[k] = v
        
    print(f"[+] Total merged configuration options: {len(merged)}")
    
    # 4. Format and write out
    lines_out = [
        "#",
        "# Automatically generated by Pure Kernel Defconfig Merger",
        "# Merged from: kona-perf_defconfig + sm8250-common.config + alioth.config + Pure Kernel Overrides",
        "#",
        ""
    ]
    
    for k in sorted(merged.keys()):
        v = merged[k]
        if v == 'n':
            lines_out.append(f"# CONFIG_{k} is not set")
        else:
            lines_out.append(f"CONFIG_{k}={v}")
            
    with open(target_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines_out) + '\n')
    print(f"[+] Successfully written merged defconfig to: {target_path}")
    
    # 5. Run compatibility test gate
    test_script = os.path.join(base_dir, "scripts/test_kernel_compatibility.py")
    if os.path.exists(test_script):
        print("[*] Running ISO 29119 compatibility quality gate...")
        res = subprocess.run([sys.executable, test_script, target_path])
        if res.returncode != 0:
            print("[!] Error: Compatibility tests failed!")
            sys.exit(1)
        print("[+] All compatibility tests PASSED.")
    return 0

if __name__ == "__main__":
    base = sys.argv[1] if len(sys.argv) > 1 else "."
    sys.exit(merge_defconfig(base))
